/** @type {import('next').NextConfig} */
const nextConfig = {
  // This allows the UI to display code generated by the agents
  eslint: {
    ignoreDuringBuilds: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
};

export default nextConfig;